Stock-App Search PR (Task #7)
ilsave/MobileFirstHomework pull request #3
Opened 2023-10-14 19:52 UTC by Oleg-root

- Added search functionality
- API calls were rewritten so now it's fast and runs on coroutines
- Minor design fixes (in search)

https://github.com/ilsave/MobileFirstHomework/assets/66378206/58fe1755-c7c6-4cf4-8f86-23ffe67f3b82

2023-10-15 20:00 UTC, ilsave commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetSearchResultsUseCase.kt
> +            repository.getStocksByQuery(params, 5, "NASDAQ")
давай вынесем константы в companion object

2023-10-15 20:02 UTC, ilsave commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetSearchResultsUseCase.kt
> +            coroutineScope {
давай выберем один стиль использования корутин, либо CoroutineScope(Dispatchers.IO).async {, либо coroutineScope {

2023-10-15 20:03 UTC, ilsave commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetStocksDataUsecase.kt
> +            coroutineScope {
можно на самом верху у функции вызвать withContext(Dispatchers.IO ) и не создавать каждый раз скоуп)

2023-10-15 20:03 UTC, ilsave commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/presentation/MainViewModel.kt
> +                delay(400)
для чего эта задержка ?

2023-10-15 20:05 UTC, ilsave commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetStocksDataUsecase.kt
> +            repository.getStocksList().filter { it.exchangeShortName == "NASDAQ" }.shuffled()
константа в компениан объект)

2023-10-15 20:33 UTC, Oleg-root commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/presentation/MainViewModel.kt
> +                delay(400)
debounce поиска 0.4 секунды

2023-10-16 12:55 UTC, LuckyDmitry requested changes

2023-10-16 12:55 UTC, indie-contributor commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/data/DataRepositoryImpl.kt
> +        val response = api.getStocksByQuery(query, limit, exchange)
Давай уберем эту переменную, она будто лишняя

2023-10-16 12:55 UTC, indie-contributor commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetSearchResultsUseCase.kt
> +            searchResultsString = searchResultsString.plus(element.symbol).plus(',')
Давай оператор reduce заиспользуем тут

2023-10-16 12:55 UTC, indie-contributor commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetSearchResultsUseCase.kt
> +        searchResultsString = searchResultsString.dropLast(1)
А если у нас нету акций и пустая строка? Что будет ? Краш?

2023-10-16 12:55 UTC, indie-contributor commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetSearchResultsUseCase.kt
> +        val result = dataPreparationHelper.combineForUI(stocksData, stocksPictures)
Вроде получаем результат, потом еще раз надо toUI делать, давай в один метод совместим

2023-10-16 12:55 UTC, indie-contributor commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetStocksDataUsecase.kt
>          val firstTenStocks = stocksList.subList(0, 10)
Константы вынести и что если в списке у нас меньше, чем 10 акций?

2023-10-16 12:55 UTC, indie-contributor commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetStocksDataUsecase.kt
> +        firstTenStocksString = firstTenStocksString.dropLast(1)
Давай всю логику туда раскидаем по private методам

2023-10-16 12:55 UTC, indie-contributor commented on Oleg/app/src/main/java/com/example/cleanarchitectureshowcase/features/home/presentation/StocksAdapter.kt
>      private var pics: List<StockPictureDTO> = listOf()
Не сокращай лучше имена, пусть будет более явным
stockPictures

2023-10-19 07:54 UTC, LuckyDmitry commented
Давай следующие ветки с более четкими названиями, приложение-шаг-функционал

2023-11-05 15:18 UTC, merged